[package]
name = "matrix-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "*"
blake2 = { version = "0.10.6", optional = true }
rayon = { version = "1.10.0", optional = true }

[dev-dependencies]
rand = "*"

[features]
default = []
hasher = ["blake2"]
rayon = ["dep:rayon"]